### ISSUE TITLE
Support for images in excel cells

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [kkAyataka/sphinxcontrib-xlsxtable#24]
Is there a way to get the images put in the excel cell to be displayed?

For example, from the below excel, only "Image below" appears in the output, but not the actual image.

![image](https://user-images.githubusercontent.com/105263271/226861423-5435d868-7449-467a-930a-04c297a7c59f.png)

**Comment by kkAyataka** [comment]
This extension does not support images. I didn't know that Excel allows for embedding images within a cell.

I researched OpenPyXL features. But it did not get images from an Excel file.

I researched the Open XML format. I will be able to get images from an Excel file directly. But it takes work.
