### ISSUE TITLE
Getting Exception From New Version

### ISSUE THREAD

**Issue by stevenjorgensen67** [kkAyataka/sphinxcontrib-xlsxtable#34]
My script worked until 2 days ago. It grabs the latest version of xlsxtable. I am now getting:

sphinx-build -M html "source" "doc_build"  
Running Sphinx v6.2.1

Exception occurred:
  File "/nis/asic/ws03/stevej/rnd-docs/docs/.test/lib/python3.10/site-packages/sphinxcontrib/xlsxtable/__init__.py", line 8, in setup
    xlsxtable.setup(app)
NameError: name 'xlsxtable' is not defined
The full traceback has been saved in /tmp/sphinx-err-80nav3b7.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by stevenjorgensen67** [comment]
Backed the version to 1.0.0 and it works.

**Comment by kkAyataka** [comment]
Thank you for your feedback. I checked v1.1.0 it is broken. I thought I had tested it, but the conditions were wrong...

**Comment by kkAyataka** [comment]
I released [v1.1.1](https://pypi.org/project/sphinxcontrib-xlsxtable/).

**Comment by stevenjorgensen67** [comment]
I will give it a try tomorrow.

**Comment by stevenjorgensen67** [comment]
The new release fixed the problem
